// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface UpdateProfilePreferencesRequest {
    fullName?: string;
    theme?: UpdateProfilePreferencesRequest.Theme;
    language?: UpdateProfilePreferencesRequest.Language;
    defaultService?: UpdateProfilePreferencesRequest.DefaultService;
    analysisMode?: UpdateProfilePreferencesRequest.AnalysisMode;
}

export namespace UpdateProfilePreferencesRequest {
    export const Theme = {
        Light: "light",
        Dark: "dark",
        System: "system",
    } as const;
    export type Theme = (typeof Theme)[keyof typeof Theme];
    export const Language = {
        En: "en",
        Tr: "tr",
    } as const;
    export type Language = (typeof Language)[keyof typeof Language];
    export const DefaultService = {
        UrlScanning: "url_scanning",
        FakeNews: "fake_news",
        PhishingMail: "phishing_mail",
        TwitterBot: "twitter_bot",
    } as const;
    export type DefaultService = (typeof DefaultService)[keyof typeof DefaultService];
    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
