// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slug: "slug"
 *     }
 */
export interface GetPublicDocsPageSlugRequest {
    /** Page slug (e.g., "getting-started" or "api/authentication") */
    slug: string;
    /** Git ref (branch, tag, or commit SHA) to fetch docs from */
    ref?: string;
}
