// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "q"
 *     }
 */
export interface GetPublicDocsSearchRequest {
    /** Search query */
    q: string;
    limit?: number;
    /** Git ref (branch, tag, or commit SHA) to fetch docs from */
    ref?: string;
}
