// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetPublicDocsTreeRequest {
    /** Git ref (branch, tag, or commit SHA) to fetch docs from */
    ref?: string;
}
