// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "path"
 *     }
 */
export interface GetPublicDocsAssetsPathRequest {
    /** Asset path relative to docs directory */
    path: string;
    /** Git ref (branch, tag, or commit SHA) to fetch docs from */
    ref?: string;
}
