// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PostPublicDocsWebhookRequest {
    ref?: string;
    repository?: PostPublicDocsWebhookRequest.Repository;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace PostPublicDocsWebhookRequest {
    export interface Repository {
        full_name: string;
    }
}
