// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface AnalysisGatewaySuccessResponse {
    success: boolean;
    data?: (unknown | null) | undefined;
    analytics?: (unknown | null) | undefined;
    meta: SecsuiteApi.AnalysisGatewayMeta;
}
