// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface AnalysisGatewayErrorResponse {
    success: boolean;
    analytics?: (unknown | null) | undefined;
    error: AnalysisGatewayErrorResponse.Error_;
    meta: SecsuiteApi.AnalysisGatewayMeta;
}

export namespace AnalysisGatewayErrorResponse {
    export interface Error_ {
        code: string;
        message: string;
        details?: (unknown | null) | undefined;
    }
}
