// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyCreateResponse {
    success: boolean;
    data: ApiKeyCreateResponse.Data;
}

export namespace ApiKeyCreateResponse {
    export interface Data {
        id: string;
        name: string | null;
        key: string;
        prefix: string | null;
        start: string | null;
        enabled: boolean;
        requestCount: number;
        remaining: number | null;
        lastRequest: string | null;
        expiresAt: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
