// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface ApiKeyListResponse {
    success: boolean;
    data: ApiKeyListResponse.Data;
}

export namespace ApiKeyListResponse {
    export interface Data {
        items: SecsuiteApi.ApiKeyUsageItem[];
    }
}
