// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyActionResponse {
    success: boolean;
    data: ApiKeyActionResponse.Data;
}

export namespace ApiKeyActionResponse {
    export interface Data {
        id: string;
        enabled?: boolean | undefined;
        deleted?: boolean | undefined;
    }
}
