// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyUsageItem {
    id: string;
    name: string | null;
    prefix: string | null;
    start: string | null;
    enabled: boolean;
    requestCount: number;
    remaining: number | null;
    rateLimitEnabled: boolean;
    rateLimitMax: number | null;
    rateLimitTimeWindow: number | null;
    lastRequest: string | null;
    expiresAt: string | null;
    createdAt: string;
    updatedAt: string;
}
