// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyUsageSummaryResponse {
    success: boolean;
    data: ApiKeyUsageSummaryResponse.Data;
}

export namespace ApiKeyUsageSummaryResponse {
    export interface Data {
        totalKeys: number;
        activeKeys: number;
        disabledKeys: number;
        totalRequests: number;
        lastRequestAt: string | null;
    }
}
