// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface BotDetectionSubgraphResponse {
    target_twitter_id: string;
    nodes: SecsuiteApi.BotDetectionNodePrediction[];
}
