// This file was auto-generated by Fern from our API Definition.

/**
 * Prediction details for one node in the sampled neighborhood.
 */
export interface BotDetectionNodePrediction {
    /** Original Twitter ID for the node */
    twitter_id: string;
    /** True only for the requested node */
    is_target: boolean;
    /** Shortest hop distance from target in the sampled graph */
    hops: number;
    prediction: string;
    bot_probability: number;
}
