// This file was auto-generated by Fern from our API Definition.

/**
 * Liveness/readiness response.
 */
export interface BotDetectionHealthResponse {
    status: string;
    timestamp: string;
    model_loaded: boolean;
}
