// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface BotDetectionGatewayErrorResponse {
    success: boolean;
    analytics?: (unknown | null) | undefined;
    error: BotDetectionGatewayErrorResponse.Error_;
    meta: SecsuiteApi.BotDetectionGatewayMeta;
}

export namespace BotDetectionGatewayErrorResponse {
    export interface Error_ {
        code: string;
        message: string;
        details?: (unknown | null) | undefined;
    }
}
