// This file was auto-generated by Fern from our API Definition.

export interface BotDetectionNodePrediction {
    twitter_id: string;
    is_target: boolean;
    hops: number;
    prediction: string;
    bot_probability: number;
}
