// This file was auto-generated by Fern from our API Definition.

export interface BotDetectionGatewayMeta {
    cache: BotDetectionGatewayMeta.Cache;
    latencyMs: number;
    sourceService: string;
    modelVersion: string;
    analysisMode: BotDetectionGatewayMeta.AnalysisMode;
    executionPath?: string | undefined;
    httpStatus: number;
}

export namespace BotDetectionGatewayMeta {
    export interface Cache {
        hit: boolean;
        key: string;
    }

    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
