// This file was auto-generated by Fern from our API Definition.

export interface BulkDeleteHistoryResponse {
    success: boolean;
    data: BulkDeleteHistoryResponse.Data;
}

export namespace BulkDeleteHistoryResponse {
    export interface Data {
        deleted: number;
    }
}
