// This file was auto-generated by Fern from our API Definition.

export interface CreateDesktopCodeResponse {
    /** One-time authorization code (64-char hex) */
    code: string;
    /** ISO 8601 expiration timestamp */
    expiresAt: string;
    /** Full deep link URL to redirect the desktop app */
    deepLinkUrl: string;
}
