// This file was auto-generated by Fern from our API Definition.

export interface DeleteHistoryResponse {
    success: boolean;
    data: DeleteHistoryResponse.Data;
}

export namespace DeleteHistoryResponse {
    export interface Data {
        deleted: number;
    }
}
