// This file was auto-generated by Fern from our API Definition.

export interface DesktopSessionUser {
    id: string;
    name: string;
    email: string;
    emailVerified: boolean;
    image?: (string | null) | undefined;
}
