// This file was auto-generated by Fern from our API Definition.

export interface ExchangeDesktopCodeResponse {
    /** Whether the exchange was successful */
    success: boolean;
    /** Session token for the desktop app to store locally */
    sessionToken?: string | undefined;
    /** URL to redirect to after successful exchange */
    redirectTo?: string | undefined;
}
