// This file was auto-generated by Fern from our API Definition.

export interface FakeNewsNewsAnalysisResponse {
    risk_level: string;
    credibility_score: number;
    inference_time_ms: number;
    suspicious_words: string[];
    reasoning: string;
}
