// This file was auto-generated by Fern from our API Definition.

export interface FakeNewsValidationError {
    loc: FakeNewsValidationError.Loc.Item[];
    msg: string;
    type: string;
    input?: unknown | undefined;
    ctx?: Record<string, unknown> | undefined;
}

export namespace FakeNewsValidationError {
    export type Loc = Loc.Item[];

    export namespace Loc {
        export type Item = string | number;
    }
}
