// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface GatewayErrorResponse {
    success: boolean;
    analytics?: (unknown | null) | undefined;
    error: GatewayErrorResponse.Error_;
    meta: SecsuiteApi.GatewayMeta;
}

export namespace GatewayErrorResponse {
    export interface Error_ {
        code: string;
        message: string;
        details?: (unknown | null) | undefined;
    }
}
