// This file was auto-generated by Fern from our API Definition.

export interface HistoryItem {
    id: string;
    inputType: string;
    inputPreview: string;
    cacheHit: boolean;
    latencyMs: number | null;
    httpStatus: number | null;
    sourceService: string | null;
    modelVersion: string | null;
    createdAt: string;
    status: string;
    errorMessage: string | null;
}
