// This file was auto-generated by Fern from our API Definition.

export interface HistoryNotFoundResponse {
    success: boolean;
    error: HistoryNotFoundResponse.Error_;
}

export namespace HistoryNotFoundResponse {
    export interface Error_ {
        code: Error_.Code;
        message: string;
    }

    export namespace Error_ {
        export const Code = {
            NotFound: "NOT_FOUND",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
