// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface HistoryListResponse {
    success: boolean;
    data: HistoryListResponse.Data;
}

export namespace HistoryListResponse {
    export interface Data {
        items: SecsuiteApi.HistoryItem[];
        page: number;
        pageSize: number;
        total: number;
        totalPages: number;
    }
}
