// This file was auto-generated by Fern from our API Definition.

export interface HistoryBadRequestResponse {
    success: boolean;
    error: HistoryBadRequestResponse.Error_;
}

export namespace HistoryBadRequestResponse {
    export interface Error_ {
        code: Error_.Code;
        message: string;
    }

    export namespace Error_ {
        export const Code = {
            BadRequest: "BAD_REQUEST",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
