// This file was auto-generated by Fern from our API Definition.

export interface HistoryDetailResponse {
    success: boolean;
    data: HistoryDetailResponse.Data;
}

export namespace HistoryDetailResponse {
    export interface Data {
        id: string;
        inputHash: string;
        cacheKey: string | null;
        cacheHit: boolean;
        inputType: string;
        inputPreview: string;
        inputValue: string;
        status: string;
        result?: (unknown | null) | undefined;
        analytics?: (unknown | null) | undefined;
        errorMessage: string | null;
        latencyMs: number | null;
        httpStatus: number | null;
        sourceService: string | null;
        modelVersion: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
