// This file was auto-generated by Fern from our API Definition.

export interface LatestJson {
    version?: string | undefined;
    notes?: string | undefined;
    pub_date?: string | undefined;
    /** Platform-specific update info */
    platforms?: Record<string, unknown> | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
