// This file was auto-generated by Fern from our API Definition.

export interface MigrateGuestHistoryResponse {
    success: boolean;
    data: MigrateGuestHistoryResponse.Data;
}

export namespace MigrateGuestHistoryResponse {
    export interface Data {
        migrated: number;
    }
}
