// This file was auto-generated by Fern from our API Definition.

export interface PhishingGatewayMeta {
    cache: PhishingGatewayMeta.Cache;
    latencyMs: number;
    sourceService: string;
    modelVersion: string;
    analysisMode: PhishingGatewayMeta.AnalysisMode;
    executionPath?: string | undefined;
    httpStatus: number;
}

export namespace PhishingGatewayMeta {
    export interface Cache {
        hit: boolean;
        key: string;
    }

    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
