// This file was auto-generated by Fern from our API Definition.

export interface PhishingValidationError {
    loc: PhishingValidationError.Loc.Item[];
    msg: string;
    type: string;
}

export namespace PhishingValidationError {
    export type Loc = Loc.Item[];

    export namespace Loc {
        export type Item = string | number;
    }
}
