// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

export interface PhishingGatewayErrorResponse {
    success: boolean;
    analytics?: (unknown | null) | undefined;
    error: PhishingGatewayErrorResponse.Error_;
    meta: SecsuiteApi.PhishingGatewayMeta;
}

export namespace PhishingGatewayErrorResponse {
    export interface Error_ {
        code: string;
        message: string;
        details?: (unknown | null) | undefined;
    }
}
