// This file was auto-generated by Fern from our API Definition.

export interface PhishingEmailResponse {
    is_phishing: boolean;
    threat_score_out_of_100: number;
    reasoning: string;
    inference_time_ms: number;
}
