// This file was auto-generated by Fern from our API Definition.

export interface ProfilePreferencesResponse {
    success: boolean;
    data: ProfilePreferencesResponse.Data;
}

export namespace ProfilePreferencesResponse {
    export interface Data {
        email: string;
        fullName: string;
        theme: Data.Theme;
        language: Data.Language;
        defaultService: Data.DefaultService;
        analysisMode: Data.AnalysisMode;
    }

    export namespace Data {
        export const Theme = {
            Light: "light",
            Dark: "dark",
            System: "system",
        } as const;
        export type Theme = (typeof Theme)[keyof typeof Theme];
        export const Language = {
            En: "en",
            Tr: "tr",
        } as const;
        export type Language = (typeof Language)[keyof typeof Language];
        export const DefaultService = {
            UrlScanning: "url_scanning",
            FakeNews: "fake_news",
            PhishingMail: "phishing_mail",
            TwitterBot: "twitter_bot",
        } as const;
        export type DefaultService = (typeof DefaultService)[keyof typeof DefaultService];
        export const AnalysisMode = {
            Hybrid: "hybrid",
            MlOnly: "ml_only",
            LlmOnly: "llm_only",
        } as const;
        export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
    }
}
