// This file was auto-generated by Fern from our API Definition.

/**
 * Headless browser screenshot capture.
 */
export interface ScanningScreenshotResult {
    success?: boolean | undefined;
    file_path?: (string | null) | undefined;
    url?: (string | null) | undefined;
    error?: (string | null) | undefined;
}
