// This file was auto-generated by Fern from our API Definition.

/**
 * SSL / TLS certificate analysis.
 */
export interface ScanningSslResult {
    is_valid?: boolean | undefined;
    issuer?: (string | null) | undefined;
    subject?: (string | null) | undefined;
    serial_number?: (string | null) | undefined;
    not_before?: (string | null) | undefined;
    not_after?: (string | null) | undefined;
    days_until_expiry?: (number | null) | undefined;
    san_list?: string[] | undefined;
    san_matches_domain?: boolean | undefined;
    protocol_version?: (string | null) | undefined;
    key_size?: (number | null) | undefined;
    key_type?: (string | null) | undefined;
    chain_length?: (number | null) | undefined;
    is_self_signed?: boolean | undefined;
    error?: (string | null) | undefined;
}
