// This file was auto-generated by Fern from our API Definition.

/**
 * LongFormer malicious script detection.
 */
export interface ScanningScriptMlResult {
    is_malicious?: boolean | undefined;
    confidence?: (number | null) | undefined;
    error?: (string | null) | undefined;
}
