// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

/**
 * Aggregated reputation data.
 */
export interface ScanningReputationResult {
    whois?: SecsuiteApi.ScanningWhoisInfo | undefined;
    dns?: SecsuiteApi.ScanningDnsInfo | undefined;
    tranco_rank?: (number | null) | undefined;
    error?: (string | null) | undefined;
}
