// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

/**
 * Results from conditional file download analysis.
 */
export interface ScanningFileAnalysisResult {
    was_downloaded?: boolean | undefined;
    content_type?: (string | null) | undefined;
    file_extension?: (string | null) | undefined;
    sha256_hash?: (string | null) | undefined;
    file_size_bytes?: (number | null) | undefined;
    malware_detection?: SecsuiteApi.ScanningMalwareMlResult | undefined;
    script_detection?: SecsuiteApi.ScanningScriptMlResult | undefined;
    error?: (string | null) | undefined;
}
