// This file was auto-generated by Fern from our API Definition.

export interface ScanningWhoisInfo {
    domain_name?: (string | null) | undefined;
    creation_date?: (string | null) | undefined;
    expiration_date?: (string | null) | undefined;
    domain_age_days?: (number | null) | undefined;
    registrar?: (string | null) | undefined;
}
