// This file was auto-generated by Fern from our API Definition.

/**
 * VirusTotal URL analysis result.
 */
export interface ScanningVirusTotalResult {
    is_malicious?: boolean | undefined;
    detection_ratio?: (string | null) | undefined;
    scan_id?: (string | null) | undefined;
    vendor_results?: Record<string, string> | undefined;
    error?: (string | null) | undefined;
}
