// This file was auto-generated by Fern from our API Definition.

/**
 * Google Safe Browsing Lookup API v4 result.
 */
export interface ScanningSafeBrowsingResult {
    is_threat?: boolean | undefined;
    threats?: Record<string, unknown>[] | undefined;
    error?: (string | null) | undefined;
}
