// This file was auto-generated by Fern from our API Definition.

/**
 * Visual phishing page detection (Faster R-CNN + Siamese + domain analysis).
 */
export interface ScanningPhishingMlResult {
    is_phishing?: boolean | undefined;
    confidence?: (number | null) | undefined;
    matched_brand?: (string | null) | undefined;
    url?: (string | null) | undefined;
    match_type?: (string | null) | undefined;
    domain_match_reason?: (string | null) | undefined;
    error?: (string | null) | undefined;
}
