// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../index.js";

/**
 * Complete scan result aggregating every pipeline stage.
 */
export interface ScanningScanResponse {
    url: string;
    /** The URL after following all redirects; equals 'url' when there are none */
    final_url?: (string | null) | undefined;
    /** Ordered list of all URLs in the redirect chain (empty when no redirects) */
    redirect_chain?: string[] | undefined;
    scanned_at: string;
    safe_browsing?: SecsuiteApi.ScanningSafeBrowsingResult | undefined;
    virustotal?: SecsuiteApi.ScanningVirusTotalResult | undefined;
    reputation?: SecsuiteApi.ScanningReputationResult | undefined;
    ssl?: SecsuiteApi.ScanningSslResult | undefined;
    screenshot?: SecsuiteApi.ScanningScreenshotResult | undefined;
    file_analysis?: SecsuiteApi.ScanningFileAnalysisResult | undefined;
    phishing_detection?: SecsuiteApi.ScanningPhishingMlResult | undefined;
    /** Overall 0-100 risk score (higher = more dangerous) */
    risk_score?: (number | null) | undefined;
    risk_factors?: string[] | undefined;
}
