// This file was auto-generated by Fern from our API Definition.

export interface ScanningDnsInfo {
    has_mx?: boolean | undefined;
    mx_records?: string[] | undefined;
    has_spf?: boolean | undefined;
    spf_record?: (string | null) | undefined;
    has_dmarc?: boolean | undefined;
    dmarc_record?: (string | null) | undefined;
}
