// This file was auto-generated by Fern from our API Definition.

export interface ServerConfig {
    /** Disable new user registrations */
    disableRegistration: boolean;
    /** Google OAuth available */
    hasGoogleSignIn: boolean;
    /** GitHub OAuth available */
    hasGithubSignIn: boolean;
    /** Twitter/X OAuth available */
    hasTwitterSignIn: boolean;
    /** Reddit OAuth available */
    hasRedditSignIn: boolean;
    /** Resend enabled */
    hasResend: boolean;
    /** CAPTCHA protection enabled */
    hasCaptcha: boolean;
    /** Cloudflare Turnstile site key for frontend integration */
    turnstileSiteKey: string | null;
    /** Anonymous authentication enabled */
    hasAnonymous: boolean;
    /** API key authentication enabled */
    hasApiKey: boolean;
}
