// This file was auto-generated by Fern from our API Definition.

export interface SettingsErrorResponse {
    success: boolean;
    error: SettingsErrorResponse.Error_;
}

export namespace SettingsErrorResponse {
    export interface Error_ {
        code: string;
        message: string;
    }
}
