// This file was auto-generated by Fern from our API Definition.

export const GetApiV1HistoryRequestSourceService = {
    UrlScanning: "url_scanning",
    FakeNews: "fake_news",
    PhishingMail: "phishing_mail",
    TwitterBot: "twitter_bot",
} as const;
export type GetApiV1HistoryRequestSourceService =
    (typeof GetApiV1HistoryRequestSourceService)[keyof typeof GetApiV1HistoryRequestSourceService];
