// This file was auto-generated by Fern from our API Definition.

export const GetApiV1HistoryRequestSortBy = {
    CreatedAt: "createdAt",
    LatencyMs: "latencyMs",
} as const;
export type GetApiV1HistoryRequestSortBy =
    (typeof GetApiV1HistoryRequestSortBy)[keyof typeof GetApiV1HistoryRequestSortBy];
