// This file was auto-generated by Fern from our API Definition.

export const GetApiV1HistoryRequestSortOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type GetApiV1HistoryRequestSortOrder =
    (typeof GetApiV1HistoryRequestSortOrder)[keyof typeof GetApiV1HistoryRequestSortOrder];
