// This file was auto-generated by Fern from our API Definition.

export const GetApiV1HistoryRequestInputType = {
    Url: "url",
    Username: "username",
    Email: "email",
    Ip: "ip",
    Hash: "hash",
    Article: "article",
} as const;
export type GetApiV1HistoryRequestInputType =
    (typeof GetApiV1HistoryRequestInputType)[keyof typeof GetApiV1HistoryRequestInputType];
