// This file was auto-generated by Fern from our API Definition.

import type * as SecsuiteApi from "../../../../index.js";

/**
 * @example
 *     {
 *         page: 1,
 *         pageSize: 20,
 *         cacheHit: true
 *     }
 */
export interface GetApiV1HistoryRequest {
    page?: number;
    pageSize?: number;
    inputType?: SecsuiteApi.GetApiV1HistoryRequestInputType;
    sourceService?: SecsuiteApi.GetApiV1HistoryRequestSourceService;
    cacheHit?: boolean | null;
    sortBy?: SecsuiteApi.GetApiV1HistoryRequestSortBy;
    sortOrder?: SecsuiteApi.GetApiV1HistoryRequestSortOrder;
}
