// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "c2b5ef2b-7c89-4c70-af12-5c5c216f2a2d"
 *     }
 */
export interface GetApiV1HistoryIdRequest {
    id: string;
}
