// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         guestSessionToken: "sess_abc123"
 *     }
 */
export interface MigrateGuestHistoryRequest {
    guestSessionToken: string;
}
