// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface ScanningScanRequest {
    /** The URL to analyse */
    url: string;
}
