// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "text"
 *     }
 */
export interface PhishingEmailRequest {
    /** Email body text to analyze */
    text: string;
}
