// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "Your account will be suspended. Click here to verify."
 *     }
 */
export interface PhishingEmailRequest {
    /** Analiz edilecek e-posta metni */
    text: string;
}
