// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AnalysisClient", () => {
    test("analyze_news_api_v1_analyze_news_post (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            risk_level: "risk_level",
            credibility_score: 1.1,
            inference_time_ms: 1.1,
            suspicious_words: ["suspicious_words"],
            reasoning: "reasoning",
        };

        server
            .mockEndpoint()
            .post("/fake-news/api/v1/analyze/news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.analysis.analyzeNewsApiV1AnalyzeNewsPost({
            text: "text",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("analyze_news_api_v1_analyze_news_post (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/fake-news/api/v1/analyze/news")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.analysis.analyzeNewsApiV1AnalyzeNewsPost({
                text: "x",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });
});
