// This file was auto-generated by Fern from our API Definition.

import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ConfigClient", () => {
    test("getPublicServerConfigurationFlags", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            disableRegistration: false,
            hasGoogleSignIn: true,
            hasGithubSignIn: false,
            hasTwitterSignIn: false,
            hasRedditSignIn: false,
            hasResend: true,
            hasCaptcha: true,
            turnstileSiteKey: "0x4AAAAAABxxxxxxxxxxxxxxxx",
            hasAnonymous: true,
            hasApiKey: true,
        };

        server.mockEndpoint().get("/public/config").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.config.getPublicServerConfigurationFlags();
        expect(response).toEqual(rawResponseBody);
    });
});
