// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DesktopAuthClient", () => {
    test("exchangeAOneTimeCodeForADesktopSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { code: "a1b2c3d4e5f6..." };
        const rawResponseBody = { success: true, sessionToken: "a1b2c3d4...", redirectTo: "/dashboard" };

        server
            .mockEndpoint()
            .post("/public/desktop-auth/exchange")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.desktopAuth.exchangeAOneTimeCodeForADesktopSession({
            code: "a1b2c3d4e5f6...",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("exchangeAOneTimeCodeForADesktopSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { code: "blackcurrant...................." };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/public/desktop-auth/exchange")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.desktopAuth.exchangeAOneTimeCodeForADesktopSession({
                code: "blackcurrant....................",
            });
        }).rejects.toThrow(SecsuiteApi.UnauthorizedError);
    });

    test("getDesktopSessionFromBearerToken (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            session: { id: "session_123", token: "a1b2c3d4...", expiresAt: "2026-03-01T12:00:00.000Z" },
            user: { id: "user_123", name: "Jane Doe", email: "jane@example.com", emailVerified: true, image: "image" },
        };

        server
            .mockEndpoint()
            .get("/public/desktop-auth/session")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.desktopAuth.getDesktopSessionFromBearerToken();
        expect(response).toEqual(rawResponseBody);
    });

    test("getDesktopSessionFromBearerToken (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/desktop-auth/session")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.desktopAuth.getDesktopSessionFromBearerToken();
        }).rejects.toThrow(SecsuiteApi.UnauthorizedError);
    });

    test("createAOneTimeDesktopAuthorizationCode", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            code: "a1b2c3d4e5f6...",
            expiresAt: "2026-02-12T12:05:00.000Z",
            deepLinkUrl: "ss://auth/callback?code=a1b2c3d4e5f6...&callbackURL=%2Fdashboard",
        };

        server
            .mockEndpoint()
            .post("/api/v1/desktop-auth/create-code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.desktopAuth.createAOneTimeDesktopAuthorizationCode();
        expect(response).toEqual(rawResponseBody);
    });
});
