// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DocumentationClient", () => {
    test("getDocumentationPageTree (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            name: "name",
            children: [{ type: "page", name: "name", url: "url", icon: "icon", children: [null] }],
        };

        server.mockEndpoint().get("/public/docs/tree").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.documentation.getDocumentationPageTree();
        expect(response).toEqual(rawResponseBody);
    });

    test("getDocumentationPageTree (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/public/docs/tree").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.documentation.getDocumentationPageTree();
        }).rejects.toThrow(SecsuiteApi.InternalServerError);
    });

    test("getADocumentationPage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            frontmatter: { title: "title", description: "description", icon: "icon", full: true },
            code: "code",
            toc: [{ title: "title", url: "url", depth: 1.1 }],
            url: "url",
            lastModified: "lastModified",
        };

        server
            .mockEndpoint()
            .get("/public/docs/page/slug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documentation.getADocumentationPage({
            slug: "slug",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getADocumentationPage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/docs/page/slug")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documentation.getADocumentationPage({
                slug: "slug",
            });
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("getADocumentationPage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/docs/page/slug")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documentation.getADocumentationPage({
                slug: "slug",
            });
        }).rejects.toThrow(SecsuiteApi.InternalServerError);
    });

    test("searchDocumentation", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = [
            { title: "title", description: "description", url: "url", content: "content", headings: ["headings"] },
        ];

        server
            .mockEndpoint()
            .get("/public/docs/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documentation.searchDocumentation({
            q: "q",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getSearchIndex (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            meta: { version: "version", buildTime: "buildTime", documentCount: 1.1, ref: "ref" },
            index: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/public/docs/search-index")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documentation.getSearchIndex();
        expect(response).toEqual(rawResponseBody);
    });

    test("getSearchIndex (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/docs/search-index")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documentation.getSearchIndex();
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("getDocumentationAsset (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/docs/assets/path")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documentation.getDocumentationAsset({
            path: "path",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getDocumentationAsset (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/docs/assets/path")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documentation.getDocumentationAsset({
                path: "path",
            });
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("gitHubWebhookForCacheInvalidation", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message", cacheCleared: 1.1, indexRebuilt: true };

        server
            .mockEndpoint()
            .post("/public/docs/webhook")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documentation.gitHubWebhookForCacheInvalidation();
        expect(response).toEqual(rawResponseBody);
    });
});
