// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GatewayClient", () => {
    test("scanUrlViaInternalMlGateway (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { url: "https://example.com/login" };
        const rawResponseBody = {
            success: true,
            data: { key: "value" },
            analytics: { key: "value" },
            meta: {
                cache: { hit: true, key: "key" },
                latencyMs: 1.1,
                sourceService: "sourceService",
                modelVersion: "modelVersion",
                analysisMode: "hybrid",
                executionPath: "executionPath",
                httpStatus: 1.1,
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/scan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.scanUrlViaInternalMlGateway({
            url: "https://example.com/login",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("scanUrlViaInternalMlGateway (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/scan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.scanUrlViaInternalMlGateway({
                url: "url",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("scanUrlViaInternalMlGateway (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/scan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.scanUrlViaInternalMlGateway({
                url: "url",
            });
        }).rejects.toThrow(SecsuiteApi.BadGatewayError);
    });

    test("analyzeArticleNewsTextViaInternalMlGateway (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "https://edition.cnn.com/2026/04/19/asia/north-korea-defector-intl-hnk-dst" };
        const rawResponseBody = {
            success: true,
            data: { key: "value" },
            analytics: { key: "value" },
            meta: {
                cache: { hit: true, key: "key" },
                latencyMs: 1.1,
                sourceService: "sourceService",
                modelVersion: "modelVersion",
                analysisMode: "hybrid",
                executionPath: "executionPath",
                httpStatus: 1.1,
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/analysis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.analyzeArticleNewsTextViaInternalMlGateway({
            text: "https://edition.cnn.com/2026/04/19/asia/north-korea-defector-intl-hnk-dst",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("analyzeArticleNewsTextViaInternalMlGateway (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/analysis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.analyzeArticleNewsTextViaInternalMlGateway({
                text: "x",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("analyzeArticleNewsTextViaInternalMlGateway (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/analysis")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.analyzeArticleNewsTextViaInternalMlGateway({
                text: "x",
            });
        }).rejects.toThrow(SecsuiteApi.BadGatewayError);
    });

    test("analyzeEmailTextViaPhishingMicroservice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "Your account is suspended. Click this link now." };
        const rawResponseBody = {
            success: true,
            data: { key: "value" },
            analytics: { key: "value" },
            meta: {
                cache: { hit: true, key: "key" },
                latencyMs: 1.1,
                sourceService: "sourceService",
                modelVersion: "modelVersion",
                analysisMode: "hybrid",
                executionPath: "executionPath",
                httpStatus: 1.1,
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/phishing")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.analyzeEmailTextViaPhishingMicroservice({
            text: "Your account is suspended. Click this link now.",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("analyzeEmailTextViaPhishingMicroservice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/phishing")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.analyzeEmailTextViaPhishingMicroservice({
                text: "x",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("analyzeEmailTextViaPhishingMicroservice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/phishing")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.analyzeEmailTextViaPhishingMicroservice({
                text: "x",
            });
        }).rejects.toThrow(SecsuiteApi.BadGatewayError);
    });

    test("analyzeTwitterAccountViaBotDetectionMicroservice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { twitterId: "1234567890" };
        const rawResponseBody = {
            success: true,
            data: { key: "value" },
            analytics: { key: "value" },
            meta: {
                cache: { hit: true, key: "key" },
                latencyMs: 1.1,
                sourceService: "sourceService",
                modelVersion: "modelVersion",
                analysisMode: "hybrid",
                executionPath: "executionPath",
                httpStatus: 1.1,
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/bot-detection")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.analyzeTwitterAccountViaBotDetectionMicroservice({
            twitterId: "1234567890",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("analyzeTwitterAccountViaBotDetectionMicroservice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { twitterId: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/bot-detection")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.analyzeTwitterAccountViaBotDetectionMicroservice({
                twitterId: "x",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("analyzeTwitterAccountViaBotDetectionMicroservice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { twitterId: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/bot-detection")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.analyzeTwitterAccountViaBotDetectionMicroservice({
                twitterId: "x",
            });
        }).rejects.toThrow(SecsuiteApi.BadGatewayError);
    });
});
