// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("HistoryClient", () => {
    test("getCurrentUsersAnalysisHistory", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            data: {
                items: [
                    {
                        id: "id",
                        inputType: "inputType",
                        inputPreview: "inputPreview",
                        cacheHit: true,
                        latencyMs: null,
                        httpStatus: null,
                        sourceService: null,
                        modelVersion: null,
                        createdAt: "createdAt",
                        status: "status",
                        errorMessage: null,
                    },
                ],
                page: 1.1,
                pageSize: 1.1,
                total: 1.1,
                totalPages: 1.1,
            },
        };

        server.mockEndpoint().get("/api/v1/history").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.history.getCurrentUsersAnalysisHistory({
            page: 1,
            pageSize: 20,
            cacheHit: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getOneAnalysisHistoryRecord (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            data: {
                id: "id",
                inputHash: "inputHash",
                cacheKey: "cacheKey",
                cacheHit: true,
                inputType: "inputType",
                inputPreview: "inputPreview",
                inputValue: "inputValue",
                status: "status",
                result: { key: "value" },
                analytics: { key: "value" },
                errorMessage: "errorMessage",
                latencyMs: 1.1,
                httpStatus: 1.1,
                sourceService: "sourceService",
                modelVersion: "modelVersion",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/history/c2b5ef2b-7c89-4c70-af12-5c5c216f2a2d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.history.getOneAnalysisHistoryRecord({
            id: "c2b5ef2b-7c89-4c70-af12-5c5c216f2a2d",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getOneAnalysisHistoryRecord (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/history/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.history.getOneAnalysisHistoryRecord({
                id: "id",
            });
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("deleteOneAnalysisHistoryRecord (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, data: { deleted: 1 } };

        server
            .mockEndpoint()
            .delete("/api/v1/history/c2b5ef2b-7c89-4c70-af12-5c5c216f2a2d")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.history.deleteOneAnalysisHistoryRecord({
            id: "c2b5ef2b-7c89-4c70-af12-5c5c216f2a2d",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteOneAnalysisHistoryRecord (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/history/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.history.deleteOneAnalysisHistoryRecord({
                id: "id",
            });
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("deleteMultipleAnalysisHistoryRecords (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids"] };
        const rawResponseBody = { success: true, data: { deleted: 1 } };

        server
            .mockEndpoint()
            .post("/api/v1/history/bulk-delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.history.deleteMultipleAnalysisHistoryRecords({
            ids: ["ids"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteMultipleAnalysisHistoryRecords (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { ids: ["ids", "ids"] };
        const rawResponseBody = { success: true, error: { code: "BAD_REQUEST", message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/history/bulk-delete")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.history.deleteMultipleAnalysisHistoryRecords({
                ids: ["ids", "ids"],
            });
        }).rejects.toThrow(SecsuiteApi.BadRequestError);
    });

    test("migrateGuestAnalysisHistoryToCurrentUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { guestSessionToken: "sess_abc123" };
        const rawResponseBody = { success: true, data: { migrated: 1 } };

        server
            .mockEndpoint()
            .post("/api/v1/history/migrate-guest")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.history.migrateGuestAnalysisHistoryToCurrentUser({
            guestSessionToken: "sess_abc123",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("migrateGuestAnalysisHistoryToCurrentUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { guestSessionToken: "x" };
        const rawResponseBody = { success: true, error: { code: "BAD_REQUEST", message: "message" } };

        server
            .mockEndpoint()
            .post("/api/v1/history/migrate-guest")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.history.migrateGuestAnalysisHistoryToCurrentUser({
                guestSessionToken: "x",
            });
        }).rejects.toThrow(SecsuiteApi.BadRequestError);
    });
});
