// This file was auto-generated by Fern from our API Definition.

import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("IndexClient", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { message: "SecSuite API" };

        server.mockEndpoint().get("/").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.index.get();
        expect(response).toEqual(rawResponseBody);
    });
});
