// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SecsuiteApiClient", () => {
    test("predict_predict__twitter_id__get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({
            maxRetries: 0,
            betterAuthApiKey: { apiKey: "test" },
            betterAuthSessionCookie: { sessionCookie: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            target_twitter_id: "target_twitter_id",
            nodes: [
                { twitter_id: "twitter_id", is_target: true, hops: 1, prediction: "prediction", bot_probability: 1.1 },
            ],
        };

        server
            .mockEndpoint()
            .get("/bot-detection/predict/twitter_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.predictPredictTwitterIdGet({
            twitter_id: "twitter_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("predict_predict__twitter_id__get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({
            maxRetries: 0,
            betterAuthApiKey: { apiKey: "test" },
            betterAuthSessionCookie: { sessionCookie: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/bot-detection/predict/twitter_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.predictPredictTwitterIdGet({
                twitter_id: "twitter_id",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });
});
