// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ScanClient", () => {
    test("urlScanPost (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({
            maxRetries: 0,
            betterAuthApiKey: { apiKey: "test" },
            betterAuthSessionCookie: { sessionCookie: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = {
            url: "url",
            final_url: "final_url",
            redirect_chain: ["redirect_chain"],
            scanned_at: "2024-01-15T09:30:00Z",
            safe_browsing: { is_threat: true, threats: [{ key: "value" }], error: "error" },
            virustotal: {
                is_malicious: true,
                detection_ratio: "detection_ratio",
                scan_id: "scan_id",
                vendor_results: { key: "value" },
                error: "error",
            },
            reputation: {
                whois: {
                    domain_name: "domain_name",
                    creation_date: "2024-01-15T09:30:00Z",
                    expiration_date: "2024-01-15T09:30:00Z",
                    domain_age_days: 1,
                    registrar: "registrar",
                },
                dns: {
                    has_mx: true,
                    mx_records: ["mx_records"],
                    has_spf: true,
                    spf_record: "spf_record",
                    has_dmarc: true,
                    dmarc_record: "dmarc_record",
                },
                tranco_rank: 1,
                error: "error",
            },
            ssl: {
                is_valid: true,
                issuer: "issuer",
                subject: "subject",
                serial_number: "serial_number",
                not_before: "2024-01-15T09:30:00Z",
                not_after: "2024-01-15T09:30:00Z",
                days_until_expiry: 1,
                san_list: ["san_list"],
                san_matches_domain: true,
                protocol_version: "protocol_version",
                key_size: 1,
                key_type: "key_type",
                chain_length: 1,
                is_self_signed: true,
                error: "error",
            },
            screenshot: { success: true, file_path: "file_path", url: "url", error: "error" },
            file_analysis: {
                was_downloaded: true,
                content_type: "content_type",
                file_extension: "file_extension",
                sha256_hash: "sha256_hash",
                file_size_bytes: 1,
                malware_detection: { is_malicious: true, confidence: 1.1, error: "error" },
                script_detection: { is_malicious: true, confidence: 1.1, error: "error" },
                error: "error",
            },
            phishing_detection: {
                is_phishing: true,
                confidence: 1.1,
                matched_brand: "matched_brand",
                url: "url",
                match_type: "match_type",
                domain_match_reason: "domain_match_reason",
                error: "error",
            },
            risk_score: 1.1,
            risk_factors: ["risk_factors"],
        };

        server
            .mockEndpoint()
            .post("/scanning/scan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.scan.urlScanPost({
            url: "url",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("urlScanPost (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({
            maxRetries: 0,
            betterAuthApiKey: { apiKey: "test" },
            betterAuthSessionCookie: { sessionCookie: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { url: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/scanning/scan")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.scan.urlScanPost({
                url: "x",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });
});
