// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ScannerClient", () => {
    test("scan_email_api_v1_scan_email_post (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "Your account will be suspended. Click here to verify." };
        const rawResponseBody = {
            is_phishing: true,
            threat_score_out_of_100: 1,
            reasoning: "reasoning",
            inference_time_ms: 1.1,
        };

        server
            .mockEndpoint()
            .post("/phishing/api/v1/scan-email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.scanner.scanEmailApiV1ScanEmailPost({
            text: "Your account will be suspended. Click here to verify.",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("scan_email_api_v1_scan_email_post (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/phishing/api/v1/scan-email")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.scanner.scanEmailApiV1ScanEmailPost({
                text: "text",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });
});
