// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SettingsClient", () => {
    test("getCurrentUserProfileAndDashboardPreferences", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            data: {
                email: "email",
                fullName: "fullName",
                theme: "light",
                language: "en",
                defaultService: "url_scanning",
                analysisMode: "hybrid",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/profile-preferences")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.getCurrentUserProfileAndDashboardPreferences();
        expect(response).toEqual(rawResponseBody);
    });

    test("updateCurrentUserProfileAndDashboardPreferences (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            success: true,
            data: {
                email: "email",
                fullName: "fullName",
                theme: "light",
                language: "en",
                defaultService: "url_scanning",
                analysisMode: "hybrid",
            },
        };

        server
            .mockEndpoint()
            .patch("/api/v1/settings/profile-preferences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.updateCurrentUserProfileAndDashboardPreferences();
        expect(response).toEqual(rawResponseBody);
    });

    test("updateCurrentUserProfileAndDashboardPreferences (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/settings/profile-preferences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.updateCurrentUserProfileAndDashboardPreferences();
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("listCurrentUsersApiKeysWithUsageFields", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            data: {
                items: [
                    {
                        id: "id",
                        name: null,
                        prefix: null,
                        start: null,
                        enabled: true,
                        requestCount: 1,
                        remaining: null,
                        rateLimitEnabled: true,
                        rateLimitMax: null,
                        rateLimitTimeWindow: null,
                        lastRequest: null,
                        expiresAt: null,
                        createdAt: "createdAt",
                        updatedAt: "updatedAt",
                    },
                ],
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/api-keys")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.listCurrentUsersApiKeysWithUsageFields();
        expect(response).toEqual(rawResponseBody);
    });

    test("createANewApiKeyForCurrentUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            success: true,
            data: {
                id: "id",
                name: "name",
                key: "key",
                prefix: "prefix",
                start: "start",
                enabled: true,
                requestCount: 1,
                remaining: 1,
                lastRequest: "lastRequest",
                expiresAt: "expiresAt",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };

        server
            .mockEndpoint()
            .post("/api/v1/settings/api-keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.createANewApiKeyForCurrentUser();
        expect(response).toEqual(rawResponseBody);
    });

    test("createANewApiKeyForCurrentUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/settings/api-keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.createANewApiKeyForCurrentUser();
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("getApiKeyUsageSummaryForCurrentUser", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            data: { totalKeys: 1, activeKeys: 1, disabledKeys: 1, totalRequests: 1, lastRequestAt: "lastRequestAt" },
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/api-keys/usage")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.getApiKeyUsageSummaryForCurrentUser();
        expect(response).toEqual(rawResponseBody);
    });

    test("disableAnApiKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, data: { id: "id", enabled: true, deleted: true } };

        server
            .mockEndpoint()
            .post("/api/v1/settings/api-keys/id/disable")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.disableAnApiKey({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("disableAnApiKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/settings/api-keys/id/disable")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.disableAnApiKey({
                id: "id",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("enableAnApiKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, data: { id: "id", enabled: true, deleted: true } };

        server
            .mockEndpoint()
            .post("/api/v1/settings/api-keys/id/enable")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.enableAnApiKey({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("enableAnApiKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/settings/api-keys/id/enable")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.enableAnApiKey({
                id: "id",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });

    test("deleteAnApiKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, data: { id: "id", enabled: true, deleted: true } };

        server
            .mockEndpoint()
            .delete("/api/v1/settings/api-keys/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.deleteAnApiKey({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteAnApiKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/settings/api-keys/id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.deleteAnApiKey({
                id: "id",
            });
        }).rejects.toThrow(SecsuiteApi.UnprocessableEntityError);
    });
});
