// This file was auto-generated by Fern from our API Definition.

import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SystemClient", () => {
    test("health_health_get", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "status", timestamp: "timestamp", model_loaded: true };

        server
            .mockEndpoint()
            .get("/bot-detection/health")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.system.healthHealthGet();
        expect(response).toEqual(rawResponseBody);
    });
});
