// This file was auto-generated by Fern from our API Definition.

import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SystemClient", () => {
    test("health_health_get", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({
            maxRetries: 0,
            betterAuthApiKey: { apiKey: "test" },
            betterAuthSessionCookie: { sessionCookie: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/fake-news/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.system.healthHealthGet();
        expect(response).toEqual(rawResponseBody);
    });

    test("health_check_health_get", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({
            maxRetries: 0,
            betterAuthApiKey: { apiKey: "test" },
            betterAuthSessionCookie: { sessionCookie: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/phishing/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.system.healthCheckHealthGet();
        expect(response).toEqual(rawResponseBody);
    });
});
