// This file was auto-generated by Fern from our API Definition.

import * as SecsuiteApi from "../../src/api/index";
import { SecsuiteApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UpdaterClient", () => {
    test("getLatestReleaseInfoForTauriAutoUpdater (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            version: "v0.1.0",
            notes: "Release notes",
            pub_date: "2026-01-01T00:00:00Z",
            platforms: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/public/updater/latest.json")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.updater.getLatestReleaseInfoForTauriAutoUpdater();
        expect(response).toEqual(rawResponseBody);
    });

    test("getLatestReleaseInfoForTauriAutoUpdater (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/updater/latest.json")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updater.getLatestReleaseInfoForTauriAutoUpdater();
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("getLatestReleaseInfoForTauriAutoUpdater (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/updater/latest.json")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updater.getLatestReleaseInfoForTauriAutoUpdater();
        }).rejects.toThrow(SecsuiteApi.InternalServerError);
    });

    test("downloadASpecificReleaseAssetByTagAndFilename (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        server
            .mockEndpoint()
            .get("/public/updater/download/v0.1.0/SecSuite_0.1.0_aarch64.dmg")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.updater.downloadASpecificReleaseAssetByTagAndFilename({
            tag: "v0.1.0",
            filename: "SecSuite_0.1.0_aarch64.dmg",
        });
        expect(response).toEqual(undefined);
    });

    test("downloadASpecificReleaseAssetByTagAndFilename (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/updater/download/tag/filename")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updater.downloadASpecificReleaseAssetByTagAndFilename({
                tag: "tag",
                filename: "filename",
            });
        }).rejects.toThrow(SecsuiteApi.NotFoundError);
    });

    test("downloadASpecificReleaseAssetByTagAndFilename (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SecsuiteApiClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/public/updater/download/tag/filename")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updater.downloadASpecificReleaseAssetByTagAndFilename({
                tag: "tag",
                filename: "filename",
            });
        }).rejects.toThrow(SecsuiteApi.InternalServerError);
    });
});
