// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tag: "v0.1.0",
 *         filename: "SecSuite_0.1.0_aarch64.dmg"
 *     }
 */
export interface GetPublicUpdaterDownloadTagFilenameRequest {
    tag: string;
    filename: string;
}
