// This file was auto-generated by Fern from our API Definition.

import { ConfigClient } from "./api/resources/config/client/Client.js";
import { DesktopAuthClient } from "./api/resources/desktopAuth/client/Client.js";
import { DocumentationClient } from "./api/resources/documentation/client/Client.js";
import { GatewayClient } from "./api/resources/gateway/client/Client.js";
import { HistoryClient } from "./api/resources/history/client/Client.js";
import { IndexClient } from "./api/resources/index/client/Client.js";
import { SettingsClient } from "./api/resources/settings/client/Client.js";
import { UpdaterClient } from "./api/resources/updater/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace SecsuiteApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SecsuiteApiClient {
    protected readonly _options: NormalizedClientOptions<SecsuiteApiClient.Options>;
    protected _index: IndexClient | undefined;
    protected _documentation: DocumentationClient | undefined;
    protected _config: ConfigClient | undefined;
    protected _updater: UpdaterClient | undefined;
    protected _desktopAuth: DesktopAuthClient | undefined;
    protected _gateway: GatewayClient | undefined;
    protected _history: HistoryClient | undefined;
    protected _settings: SettingsClient | undefined;

    constructor(options: SecsuiteApiClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get index(): IndexClient {
        return (this._index ??= new IndexClient(this._options));
    }

    public get documentation(): DocumentationClient {
        return (this._documentation ??= new DocumentationClient(this._options));
    }

    public get config(): ConfigClient {
        return (this._config ??= new ConfigClient(this._options));
    }

    public get updater(): UpdaterClient {
        return (this._updater ??= new UpdaterClient(this._options));
    }

    public get desktopAuth(): DesktopAuthClient {
        return (this._desktopAuth ??= new DesktopAuthClient(this._options));
    }

    public get gateway(): GatewayClient {
        return (this._gateway ??= new GatewayClient(this._options));
    }

    public get history(): HistoryClient {
        return (this._history ??= new HistoryClient(this._options));
    }

    public get settings(): SettingsClient {
        return (this._settings ??= new SettingsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
