// This file was auto-generated by Fern from our API Definition.

import { AnalysisClient } from "./api/resources/analysis/client/Client.js";
import { PredictionClient } from "./api/resources/prediction/client/Client.js";
import { ScanClient } from "./api/resources/scan/client/Client.js";
import { ScannerClient } from "./api/resources/scanner/client/Client.js";
import { SystemClient } from "./api/resources/system/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace SecsuiteApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SecsuiteApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SecsuiteApiClient.Options>;
    protected _scan: ScanClient | undefined;
    protected _system: SystemClient | undefined;
    protected _analysis: AnalysisClient | undefined;
    protected _scanner: ScannerClient | undefined;
    protected _prediction: PredictionClient | undefined;

    constructor(options: SecsuiteApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get scan(): ScanClient {
        return (this._scan ??= new ScanClient(this._options));
    }

    public get system(): SystemClient {
        return (this._system ??= new SystemClient(this._options));
    }

    public get analysis(): AnalysisClient {
        return (this._analysis ??= new AnalysisClient(this._options));
    }

    public get scanner(): ScannerClient {
        return (this._scanner ??= new ScannerClient(this._options));
    }

    public get prediction(): PredictionClient {
        return (this._prediction ??= new PredictionClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
