// This file was auto-generated by Fern from our API Definition.

export const SecsuiteApiEnvironment = {
    Default: "https://ml-gateway.example.com",
} as const;

export type SecsuiteApiEnvironment = typeof SecsuiteApiEnvironment.Default;
