// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "https://edition.cnn.com/2026/04/19/asia/north-korea-defector-intl-hnk-dst"
 *     }
 */
export interface AnalysisGatewayRequest {
    /** Raw article/news text or an http(s) URL to an article page */
    text: string;
    modelVersion?: string;
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    analysisMode?: AnalysisGatewayRequest.AnalysisMode;
    /** Bypass cache and force fresh upstream execution. */
    forceRefresh?: boolean;
}

export namespace AnalysisGatewayRequest {
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
