// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         twitterId: "1234567890"
 *     }
 */
export interface BotDetectionGatewayRequest {
    twitterId: string;
    modelVersion?: string;
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    analysisMode?: BotDetectionGatewayRequest.AnalysisMode;
    /** Bypass cache and force fresh upstream execution. */
    forceRefresh?: boolean;
}

export namespace BotDetectionGatewayRequest {
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
