// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "Your account is suspended. Click this link now."
 *     }
 */
export interface PhishingGatewayRequest {
    text: string;
    modelVersion?: string;
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    analysisMode?: PhishingGatewayRequest.AnalysisMode;
    /** Bypass cache and force fresh upstream execution. */
    forceRefresh?: boolean;
}

export namespace PhishingGatewayRequest {
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
