// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "https://example.com/login"
 *     }
 */
export interface ScanGatewayRequest {
    url: string;
    modelVersion?: string;
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    analysisMode?: ScanGatewayRequest.AnalysisMode;
    /** Bypass cache and force fresh upstream execution. */
    forceRefresh?: boolean;
}

export namespace ScanGatewayRequest {
    /** Analysis strategy: hybrid (default), ml_only, or llm_only. */
    export const AnalysisMode = {
        Hybrid: "hybrid",
        MlOnly: "ml_only",
        LlmOnly: "llm_only",
    } as const;
    export type AnalysisMode = (typeof AnalysisMode)[keyof typeof AnalysisMode];
}
