// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CreateDesktopCodeRequest {
    /** Deep link URL scheme registered in the desktop app */
    scheme?: string;
    /** Desktop in-app redirect path after successful sign in */
    callbackURL?: string;
}
