// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "a1b2c3d4e5f6..."
 *     }
 */
export interface ExchangeDesktopCodeRequest {
    /** One-time authorization code received via deep link */
    code: string;
}
