// This file was auto-generated by Fern from our API Definition.

export interface GetPublicDocsSearchIndexResponse {
    meta: GetPublicDocsSearchIndexResponse.Meta;
    /** Serialized Orama index */
    index?: (unknown | null) | undefined;
}

export namespace GetPublicDocsSearchIndexResponse {
    export interface Meta {
        version: string;
        buildTime: string;
        documentCount: number;
        ref?: string | undefined;
    }
}
