// This file was auto-generated by Fern from our API Definition.

export interface GetPublicDocsPageSlugResponse {
    frontmatter: GetPublicDocsPageSlugResponse.Frontmatter;
    code: string;
    toc: GetPublicDocsPageSlugResponse.Toc.Item[];
    url: string;
    lastModified?: string | undefined;
}

export namespace GetPublicDocsPageSlugResponse {
    export interface Frontmatter {
        title: string;
        description?: string | undefined;
        icon?: string | undefined;
        full?: boolean | undefined;
    }

    export type Toc = Toc.Item[];

    export namespace Toc {
        export interface Item {
            title: string;
            url: string;
            depth: number;
        }
    }
}
