// This file was auto-generated by Fern from our API Definition.

export interface GetPublicDocsTreeResponse {
    name: string;
    children: GetPublicDocsTreeResponse.Children.Item[];
}

export namespace GetPublicDocsTreeResponse {
    export type Children = Children.Item[];

    export namespace Children {
        export interface Item {
            type: Item.Type;
            name: string;
            url?: string | undefined;
            icon?: string | undefined;
            children?: (unknown | null)[] | undefined;
        }

        export namespace Item {
            export const Type = {
                Page: "page",
                Folder: "folder",
                Separator: "separator",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }
}
