// This file was auto-generated by Fern from our API Definition.

export interface GetPublicDocsSearchResponseItem {
    title: string;
    description?: string | undefined;
    url: string;
    content: string;
    headings?: string[] | undefined;
}
