// This file was auto-generated by Fern from our API Definition.

export interface PostPublicDocsWebhookResponse {
    message: string;
    cacheCleared?: number | undefined;
    indexRebuilt?: boolean | undefined;
}
